targetNamespace: ''
parameters: {}
packages:
  - name: kai-helper
    environment: {}
    parameters: {}
    annotations: {}
    actions:
      - name: kai-helper
        binary: false
        main: ''
        runtime: 'python:default'
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits:
          timeout: 30000
          memory: 512
